### ISSUE TITLE
Выше вы успешно использовали синтаксис get type() { ... }. В чем преимущество использования objectDefineProperty здесь?

### ISSUE THREAD

**Issue by frontgirl** [ingaKuus/JSDiploma#12]
https://github.com/ingaKuus/JSDiploma/blob/46f47e47e9bd7fe3177cffa33b5854fcaf88f7d5/game.js#L206

**Comment by ingaKuus** [comment]
Действительно, ни в чем; заменила все Object.defineProperty на геттеры
