### ISSUE TITLE
для перебора следует использовать for ... of или forEach/map

### ISSUE THREAD

**Issue by frontgirl** [ingaKuus/JSDiploma#7]
https://github.com/ingaKuus/JSDiploma/blob/8f617452449bc05fc52db6ece3107f82ad2c303f/game.js#L182

Также i (как и j в методе ниже) - не очень хорошие названия для переменных, давайте назовем эти переменные в соответствии с их содержимым.

**Comment by ingaKuus** [comment]
Переборы строк заменила
